db.persons.insertMany([
  {
    _id: "john.doe@example.com",
    vorname: "John",
    nachname: "Doe",
    geschlecht: "männlich",
    telefon: "+1234567890",
    email: "john.doe@example.com",
  },
  {
    _id: "jane.smith@example.com",
    vorname: "Jane",
    nachname: "Smith",
    telefon: "+0987654321",
    email: "jane.smith@example.com",
  },
  {
    _id: "emma.jackson@example.com",
    vorname: "Emma",
    nachname: "Jackson",
    geschlecht: "weiblich",
    telefon: "+1122334455",
    email: "emma.jackson@example.com",
  },
  {
    _id: "james.brown@example.com",
    vorname: "James",
    nachname: "Brown",
    geschlecht: "männlich",
    telefon: "+3344556677",
    email: "james.brown@example.com",
  },
  {
    _id: "sophie.wilson@example.com",
    vorname: "Sophie",
    nachname: "Wilson",
    geschlecht: "weiblich",
    telefon: "+5566778899",
    email: "sophie.wilson@example.com",
  },
  {
    _id: "michael.adams@example.com",
    vorname: "Michael",
    nachname: "Adams",
    telefon: "+9900112233",
    email: "michael.adams@example.com",
  },
  {
    _id: "sarah.johnson@example.com",
    vorname: "Sarah",
    nachname: "Johnson",
    telefon: "+968736248",
    email: "sarah.johnson@example.com",
  },

  {
    _id: "emily.miller@example.com",
    vorname: "Emily",
    nachname: "Miller",
    geschlecht: "weiblich",
    telefon: "+5250693634",
    email: "emily.miller@example.com",
  },
  {
    _id: "oliver.jackson@example.com",
    vorname: "Oliver",
    nachname: "Jackson",
    geschlecht: "männlich",
    telefon: "+0104357822",
    email: "oliver.jackson@example.com",
  },
  {
    _id: "leo.martin@example.com",
    vorname: "Leo",
    nachname: "Martin",
    geschlecht: "männlich",
    telefon: "+3733715066",
    email: "leo.martin@example.com",
  },
  {
    _id: "jack.harris@example.com",
    vorname: "Jack",
    nachname: "Harris",
    geschlecht: "männlich",
    telefon: "+6187575642",
    email: "jack.harris@example.com",
  },
  {
    _id: "harry.anderson@example.com",
    vorname: "Harry",
    nachname: "Anderson",
    geschlecht: "männlich",
    telefon: "+7559734135",
    email: "harry.anderson@example.com",
  },
  {
    _id: "isabella.wilson@example.com",
    vorname: "Isabella",
    nachname: "Wilson",
    geschlecht: "weiblich",
    telefon: "+7999110490",
    email: "isabella.wilson@example.com",
  },
  {
    _id: "isabella.taylor@example.com",
    vorname: "Isabella",
    nachname: "Taylor",
    geschlecht: "weiblich",
    telefon: "+1450929980",
    email: "isabella.taylor@example.com",
  },
  {
    _id: "jack.miller@example.com",
    vorname: "Jack",
    nachname: "Miller",
    geschlecht: "männlich",
    telefon: "+8639020971",
    email: "jack.miller@example.com",
  },
  {
    _id: "mia.thomas@example.com",
    vorname: "Mia",
    nachname: "Thomas",
    geschlecht: "weiblich",
    telefon: "+5078103918",
    email: "mia.thomas@example.com",
  },
  {
    _id: "george.thomas@example.com",
    vorname: "George",
    nachname: "Thomas",
    geschlecht: "männlich",
    telefon: "+2744872540",
    email: "george.thomas@example.com",
  },
  {
    _id: "harryy.anderson@example.com",
    vorname: "Harryy",
    nachname: "Anderson",
    geschlecht: "männlich",
    telefon: "+4017404195",
    email: "harryy.anderson@example.com",
  },
  {
    _id: "leo.jackson@example.com",
    vorname: "Leo",
    nachname: "Jackson",
    geschlecht: "männlich",
    telefon: "+0092918007",
    email: "leo.jackson@example.com",
  },
  {
    _id: "alfie.moore@example.com",
    vorname: "Alfie",
    nachname: "Moore",
    geschlecht: "männlich",
    telefon: "+6810039599",
    email: "alfie.moore@example.com",
  },
  {
    _id: "isla.white@example.com",
    vorname: "Isla",
    nachname: "White",
    geschlecht: "weiblich",
    telefon: "+1174856364",
    email: "isla.white@example.com",
  },
  {
    _id: "jack.thomas@example.com",
    vorname: "Jack",
    nachname: "Thomas",
    geschlecht: "männlich",
    telefon: "+1962355341",
    email: "jack.thomas@example.com",
  },
]);
